### ISSUE TITLE
更新了订阅之后，无法选择服务器节点了

### ISSUE THREAD

**Issue by wizos** [bannedbook/v2ray.vpn#1]
Please read contributing guidelines. Thanks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android/Chrome OS version: [e.g. "7.0.0_r14" or "71.0.3578.94 (32-bit)", more detailed description is preferred]
 - Device: [e.g. Google Pixel XL]
 - Version: [e.g. version code "v3.0.0" or commit ID "a073f85"]
 - Last version that did not exhibit the issue: [not applicable]

**Configuration**
Put an `x` inside the [ ] that applies.

* [ ] IPv4 server address
* [ ] IPv6 server address
* [ ] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: 8.8.8.8
* [ ] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* If you're not using VPN mode, please supply more details here:

**Additional context**

**Comment by bannedbook** [comment]
从哪更新的，什么版本？

**Comment by wizos** [comment]
下载最新的源代码自己编译的，在添加订阅地址并更新后，就无法切换节点了。
测试发现是 MainActivity 的 onCreate 方法中，通过 connection.connect(this, this) 这句最终没有成功执行 ShadowsocksConnection onServiceConnected 方法

**Comment by bannedbook** [comment]
换这个 aar
https://github.com/bannedbook/ssvpn/raw/814b94b9e8a8061ec8dbee3ef59ec719551e844c/libv2ray/libv2ray.aar

**Comment by wizos** [comment]
成功解决，非常感谢！
