### ISSUE TITLE
局域网共享udp不支持

### ISSUE THREAD

**Issue by YuIosXiao** [bannedbook/v2ray.vpn#2]
请提供一下思路，怎么去支持局域网共享支持udp这个功能

**Comment by bannedbook** [comment]
如果共享一个 socks 代理 或许可以支持

**Comment by YuIosXiao** [comment]
我现在想用手机分享热点给主机加速游戏用，想研究这方面的东西，应该怎样做，大体的思路是怎样的

**Comment by 2fdnkpj** [comment]
google play 搜索 NetShare（有很多，有root版和非root版，想用哪个自己选择），软件都大同小异。用时需要将ssvpn 和NetShare软件同时开启，连接设备需要在同一网段，非WiFi环境手机分享热点也行，把需要连接的设备的网络代理地址设置成NetShare共享地址即可，一般只需要填写ip地址和端口即可，无需密码。

**Comment by 2fdnkpj** [comment]
只要ssvpn 中的线路连接速度快且稳定，用NetShare分享出去的代理连接也是很稳定的。
