### ISSUE TITLE
能否加入IPLC专线？

### ISSUE THREAD

**Issue by ghost** [bannedbook/v2ray.vpn#20]
IPLC 全称 International Private Leased Circuit ，大学校园网、跨国企业都可能有专线直达外国；这种专线是不过墙的，然而普通的VPN和代理的必经之路是GFW，因此IPLC比普通VPN更好。能否加入IPLC节点？采用IPLC，国内和国外的通信就不会经过GFW。但还有一些要求：如果IPLC必须用中国三大运营商（移动、联通、电信），就请确保V2Ray流量在落地机解密。如果专线的入口只能用国内三大运营商，V2Ray流量采用AES或ChaCha20加密，就不能在专线的入口处急忙解密，而是把流量发到外国落地机，落地机再用密钥来解密AES或ChaCha20的流量。

**Comment by ghost** [comment]
@bannedbook 如果IPLC必须用中国三大运营商（移动、联通、电信），就请确保V2Ray流量在落地机解密。如果专线的入口只能用国内三大运营商，V2Ray流量采用AES或ChaCha20加密，就不能在专线的入口处急忙解密，而是把流量发到外国落地机，落地机再用密钥来解密AES或ChaCha20的流量。

**Comment by bannedbook** [comment]
我们没有这方面的资源
