### ISSUE TITLE
AGPL的代码能否合并？

### ISSUE THREAD

**Issue by ghost** [bannedbook/v2ray.vpn#23]
https://github.com/oilel/pqt 我写的代码采用 AGPL 3.0 作许可证，其实也包含第三方代码，第三方代码有的采用MIT或Apache的，但是主要代码采用AGPL3.0。如果接受这款许可证的话，考虑下能否合并。

**Comment by bannedbook** [comment]
啥代码

**Comment by ghost** [comment]
> 啥代码

用后量子加密（Kyber1024配合三重AES）。Kyber1024的安全性可以 提到：Kyber-1024 is known to have 254 bits of classical security and 230 bits of quantum security (coreSVP hardness). 但是Kyber公钥要通过安全的方法传输到用户的设备，比如通过SSH或TLS。现在的SSH和TLS仍旧采用RSA或ECC算法，传输个Kyber公钥还没问题，这一步没有传输敏感数据；等到现在的RSA或ECC加密被量子计算机破解以后，看到的就只有Kyber公钥了，通过 SSH或TLS传输的Kyber公钥。

**Comment by ghost** [comment]
之前有一些逻辑漏洞。0.3.4版本修复了这些漏洞。 @bannedbook
