### ISSUE TITLE
创建vpn

### ISSUE THREAD

**Issue by Aaronoooooo** [bannedbook/v2ray.vpn#5]
点击连接提示创建vpn服务权限不足

**Comment by bannedbook** [comment]
哪个软件

**Comment by Aaronoooooo** [comment]
> 哪个软件

SS VPN
![image](https://user-images.githubusercontent.com/46308307/110086736-b39b5000-7dcd-11eb-9e0a-9841cfb9ccc3.png)

**Comment by bannedbook** [comment]
参考
https://www.google.com/search?q=ss+%E5%88%9B%E5%BB%BAvpn%E6%9C%8D%E5%8A%A1%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3

**Comment by Aaronoooooo** [comment]
> 参考
> https://www.google.com/search?q=ss+%E5%88%9B%E5%BB%BAvpn%E6%9C%8D%E5%8A%A1%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3

好的,谢谢
