### ISSUE TITLE
pc support

### ISSUE THREAD

**Issue by klt14** [bannedbook/v2ray.vpn#8]
Much thanks for your work! However, I think it would be great if v2ray VPN could support usage on PC. Alternatives like Freegate or Psiphon does not support connection from LAN, which is a quite conveninent feature of V2ray.

**Comment by bannedbook** [comment]
try this one
https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85

**Comment by klt14** [comment]
Thanks for information!
