### ISSUE TITLE
请求默认开启IPv6路由

### ISSUE THREAD

**Issue by ghost** [bannedbook/v2ray.vpn#9]
IPv6路由默认禁用会导致部分流量不经过代理，有安全隐患。

**Comment by bannedbook** [comment]
建议禁用 客户端 ipv6 网络

**Comment by hojarasca2** [comment]
> 建议禁用 客户端 ipv6 网络
为何？

**Comment by ghost** [comment]
> 建议禁用 客户端 ipv6 网络

为何？

**Comment by bannedbook** [comment]
> > 建议禁用 客户端 ipv6 网络
> 
> 为何？

禁用了就不存在你说的问题了
